name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:  # Enable manual triggering for testing
    inputs:
      issue_or_pr_number:
        description: 'Issue or PR number to respond to'
        required: true
        type: number
      prompt:
        description: 'Custom prompt for Claude (optional)'
        required: false
        type: string

jobs:
  claude:
    # Optional: Restrict to issues/PRs with specific labels to prevent accidental activations
    # if: |
    #   (github.event_name == 'workflow_dispatch') ||
    #   (contains(github.event.issue.labels.*.name, 'claude-review') || contains(github.event.pull_request.labels.*.name, 'claude-review')) &&
    #   ((github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
    #   (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
    #   (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
    #   (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude'))))

    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest

    # Prevent multiple simultaneous runs on the same issue/PR
    concurrency:
      group: claude-${{ github.event.issue.number || github.event.pull_request.number || inputs.issue_or_pr_number }}
      cancel-in-progress: true

    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full git history for better context

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read

          # Optional: Give a custom prompt to Claude. If this is not specified, Claude will perform the instructions specified in the comment that tagged it.
          # For workflow_dispatch events, uses the provided prompt input
          prompt: ${{ inputs.prompt || '' }}

          # Optional: Add claude_args to customize behavior and configuration
          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.claude.com/en/docs/claude-code/cli-reference for available options
          # claude_args: '--allowed-tools Bash(gh pr:*)'
